import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../theming/colors.dart';
import '../theming/styles.dart';

void customSnackbar(
  String title,
  String message, {
  Color? colorText,
  Duration? duration = const Duration(seconds: 3),
  bool instantInit = true,
  SnackPosition? snackPosition,
  Widget? icon,
  bool? shouldIconPulse,
  double? maxWidth,
  EdgeInsets? margin,
  EdgeInsets? padding,
  double? borderRadius,
  Color? borderColor,
  double? borderWidth,
  Color? backgroundColor,
  Color? leftBarIndicatorColor,
  List<BoxShadow>? boxShadows,
  Gradient? backgroundGradient,
  TextButton? mainButton,
  void Function(GetSnackBar)? onTap,
  bool? isDismissible,
  bool? showProgressIndicator,
  DismissDirection? dismissDirection,
  AnimationController? progressIndicatorController,
  Color? progressIndicatorBackgroundColor,
  Animation<Color>? progressIndicatorValueColor,
  SnackStyle? snackStyle,
  Curve? forwardAnimationCurve,
  Curve? reverseAnimationCurve,
  Duration? animationDuration,
  double? barBlur,
  double? overlayBlur,
  void Function(SnackbarStatus?)? snackbarStatus,
  Color? overlayColor,
  Form? userInputForm,
}) {
  Get.snackbar(
    '',
    message,
    // titleText: Center(child: Text(title, textAlign: TextAlign.center, style: AppStyles.font14White500)),
    messageText: Center(child: Text(message, textAlign: TextAlign.center, style: AppStyles.font14White500)),
    colorText: colorText,
    duration: duration,
    instantInit: instantInit,
    snackPosition: snackPosition ?? SnackPosition.TOP,
    icon: icon,
    shouldIconPulse: shouldIconPulse,
    maxWidth: maxWidth,
    margin: margin,
    padding: padding,
    borderRadius: borderRadius,
    borderColor: borderColor,
    borderWidth: borderWidth,
    // ignore: deprecated_member_use
    backgroundColor: backgroundColor ?? AppColors.main.withOpacity(0.9),
    leftBarIndicatorColor: leftBarIndicatorColor,
    boxShadows: boxShadows,
    backgroundGradient: backgroundGradient,
    mainButton: mainButton,
    onTap: onTap,
    isDismissible: isDismissible,
    showProgressIndicator: showProgressIndicator,
    dismissDirection: dismissDirection ?? DismissDirection.horizontal,
    progressIndicatorController: progressIndicatorController,
    progressIndicatorBackgroundColor: progressIndicatorBackgroundColor,
    progressIndicatorValueColor: progressIndicatorValueColor,
    snackStyle: snackStyle,
    forwardAnimationCurve: forwardAnimationCurve ?? Curves.easeInOutCubicEmphasized,
    reverseAnimationCurve: reverseAnimationCurve,
    animationDuration: animationDuration,
    barBlur: barBlur ?? 5,
    overlayBlur: overlayBlur,
    snackbarStatus: snackbarStatus,
    overlayColor: overlayColor,
    userInputForm: userInputForm,
  );
}
